steps:
  - uses: Slashgear/action-check-pr-title@v4.3.0
    with:
      regexp: "(chore|docs|feat|fix|refactor|test): .++" # Regex the title should match.
      helpMessage: "Example: 'feat: example of title'"
